version: '3.7'

services:
    api_gateway:
        image: api_gateway:latest
        stdin_open: true
        restart: always
        build: ./
        # command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        entrypoint: [ "sh", "entrypoint.sh"]
        # network_mode: host
        env_file:
            - .env
        volumes:
            - ./:/code
            - ./.env:/code/.env
        ports:
            - 8001:8000
    