version: '3.7'

services:
  userservice:
    stdin_open: true
    restart: always
    build: ./
    entrypoint: ["sh", "entrypoint.sh"]
    volumes:
      - ./:/code
      - ./.env:/code/.env
    # network_mode: host 
    ports:
      - "8000:8000"
    env_file:
      - .env
      

