"""empty message

Revision ID: 1506ccfa5dd8
Revises: 41eecc73e30a
Create Date: 2025-05-11 14:06:31.425208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1506ccfa5dd8'
down_revision = '41eecc73e30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pubsub_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('statusCode', sa.String(length=100), nullable=True),
    sa.Column('queue_msg', sa.TEXT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubsub_logs')
    # ### end Alembic commands ###
