"""empty message

Revision ID: 41eecc73e30a
Revises: 
Create Date: 2025-03-06 07:17:40.370219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41eecc73e30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Event title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Event description'),
    sa.Column('event_type', sa.Enum('webinar', 'workshop', 'conference', 'meetup', name='eventtype'), nullable=False, comment='Type of event (Enum)'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='Event start time'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='Event end time'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Event location'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='User ID who created the event'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Event creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Event update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='ForeignKey Event.id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID attending the event'),
    sa.Column('registered_at', sa.DateTime(), nullable=True, comment='Timestamp when user registered'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID receiving the notification'),
    sa.Column('event_id', sa.Integer(), nullable=True, comment='Related Event ID'),
    sa.Column('notification_type', sa.Enum('welcome', 'event_update', 'event_cancellation', 'reminder', name='notificationtype'), nullable=False, comment='Type of notification'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message content'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='Notification sent timestamp'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='Notification read status'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('event_attendee')
    op.drop_table('event')
    # ### end Alembic commands ###
